apiVersion: v1
kind: ConfigMap
metadata:
  name: product-db-config
  namespace: pet
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin
  POSTGRES_DB: product_db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-db-pvc
  namespace: pet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-db
  namespace: pet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      labels:
        app: product-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: product-db-config
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: product-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: product-db
  namespace: pet
spec:
  selector:
    app: product-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
