"""Add parent_id to message

Revision ID: 1824f8a6add3
Revises: e435d0d2820a
Create Date: 2025-04-09 18:14:08.845402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1824f8a6add3'
down_revision: Union[str, None] = 'e435d0d2820a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('response', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'parent_id')
    op.drop_column('messages', 'response')
    # ### end Alembic commands ###
